### PR TITLE
Define requirements and learning goals

### LINKED ISSUE #156: Define requirements and learning goals
for each exercise

### LINKED ISSUE #212: Unify references
To `{ref}`naschr``

### PR DESCRIPTION
**Pull request by sandro-elsweijer**
# Description

closes #156 
closes #212 

- [x] replace "Lernziele" with "Lerninhalte"
- [x] link previous exercises where appropriate

## Checklist

 - [x] This Pull request is associated to an issue
 - [x] New exercises include learning requirements and learning goals.

### CODE REVIEW

**Comment by sandro-elsweijer** [comment]
While editing the learning requirements I noticed, that we used different kinds of references for other pages in the book. I tried to standardize them on the fly, but then I realized, that we have more references than I expected. We should decide which style we want to use

**Comment by sandro-elsweijer** [comment]
This is also the reason for the merge conflicts

**Review by PhiSpel — COMMENTED** [review]
I really like this addition to the exercises!

1. The boxes take up quite a lot of space. is it possible to make `{panels}` fields expandable in general, or add a sort of `hide_input` tag? So that "Voraussetzungen" and "Lernziele" remains visible and the users can expand them if they want to know more.
_Edit_: This is fine, because it is _the_ most important information about the exercise.
2. So, the conflict arises because git does not understand that simply the header of the file changed? Will this conflict always arise from now on when we want to insert a label after the panel?

**Review by m-r-schenk — COMMENTED** [review]
I like the idea of having learning goals transparent for the learners. But I don't think we can do it like that....

You have to formulate learning goals in a way that you can check afterwards, if the student achieved taht goal. For example "The student should learn how to use the MATLAB command window for simple calculations" instead of "Insight in MATLAB".

To be discussed in the group meeting.

**Pull request merged**
