### PR TITLE
embedded spielbeispiele in exercises

### LINKED ISSUE #229: "Spielbeispiel" - Linear Equation Systems
- [x] Display a static rod system (inner forces in colours, like in bridge builders).
- [x] display the corresponding matrix / linear system next to it
- [x] tell Gerd, when it's finished, so he can include a hyperlink

in VL 3rd May

### LINKED ISSUE #312: To check: Can we embed the Spielbeispiele?
https://github.com/streamlit/streamlit/issues/911

### LINKED ISSUE #323: Use Spielbeispiele as separate, motivational chapters
Nice! I like it and I say we can merge this. 

That being said, I still have two comments, that we can discuss here or in a separate issue:

 - Now that we embed the streamlit apps, we could consider using a different theme *(not the dark theme)* that fits our design better. What do you think?
 - From a "story-telling" perspective I would structure the chapters differently now: We could add a small "Motivation" subchapter that introduces the method/numerical tool that is covered in the chapter, ideally with some application example. This motivation chapter should then include the embedded streamlit app to get a feeling for the tool and how it works from a user perspective. In the subsequent subchapters the reader gets the opportunity to take a look under the hood and understand how the tool works, and at the end the reader should be able to develop a similar tool using Matlab/Julia.

_Originally posted by @joergbrech in https://github.com/joergbrech/Modellbildung-und-Simulation/pull/314#pullrequestreview-945218215_

### PR DESCRIPTION
**Pull request by PhiSpel**
# Description

closes #229 
closes #312 
closes #323
alternative to pr #334 

## Checklist

 - [x] This pull request is associated to an issue
 - [x] All used resources use a CC-by-SA license or less and are marked appropriately, see our [contribution guide](https://github.com/joergbrech/Modellbildung-und-Simulation/blob/master/CONTRIBUTING.md).
 - [x] All used resources have been added to [list_of_all_resources.md](https://github.com/joergbrech/Modellbildung-und-Simulation/blob/master/docs/List_of_all_resources.md)
 - [x] Add @LeaKruehler as reviewer and wait for approval just before merging.

### CODE REVIEW

**Comment by PhiSpel** [comment]
>  - [ ] All used resources use a CC-by-SA license or less and are marked appropriately, see our [contribution guide](https://github.com/joergbrech/Modellbildung-und-Simulation/blob/master/CONTRIBUTING.md).

I could not find a CC-by-SA `LICENSE` file for my github repositories, so I used `Creative Commons Zero v1.0 Universal`.

**Comment by PhiSpel** [comment]
@LeaKruehler do we need to subscript the embedded website, too?

**Comment by LeaKruehler** [comment]
> @LeaKruehler do we need to subscript the embedded website, too?

tbh I have no clue what this is about. :D Maybe we can talk about it in the next meeting or in a call next week?

**Comment by PhiSpel** [comment]
I added a line similar to the YT line, so if one reviewer can confirm, I will embed the other pages, too.

**Review by m-r-schenk — COMMENTED** [review]
Is there a way to open the streamlit app in a new tab or fullscreen or just a link to the streamlit website to just make it bigger?

**Comment by PhiSpel** [comment]
> Is there a way to open the streamlit app in a new tab or fullscreen or just a link to the streamlit website to just make it bigger?

I added a link which opens in a new tab. Is that what you imagined?

**Review by joergbrech — DISMISSED** [review]
Nice! I like it and I say we can merge this. 

That being said, I still have two comments, that we can discuss here or in a separate issue:

 - Now that we embed the streamlit apps, we could consider using a different theme *(not the dark theme)* that fits our design better. What do you think?
 - From a "story-telling" perspective I would structure the chapters differently now: We could add a small "Motivation" subchapter that introduces the method/numerical tool that is covered in the chapter, ideally with some application example. This motivation chapter should then include the embedded streamlit app to get a feeling for the tool and how it works from a user perspective. In the subsequent subchapters the reader gets the opportunity to take a look under the hood and understand how the tool works, and at the end the reader should be able to develop a similar tool using Matlab/Julia.

**Comment by PhiSpel** [comment]
@m-r-schenk can you review the Spielbeispiele in general?

**Comment by PhiSpel** [comment]
As the highline chapter is quite extensive already, I would put the spielbeispiel-lgls as a separate chapter, here. If we want to have all as separate chapters, we can merge #334. I do think separate chapters, as @joergbrech suggested, look nicer. What do you think?

**Review by LeaKruehler — DISMISSED** [review]
looks good to me

**Pull request closed without merging**
