### PR TITLE
use latest versions of python and jupyter-book

### LINKED ISSUE #460: use the latest python and jupyter-notebook releases
We could probably also update the docker image we use, currently we are using a legacy docker image running Python 3.6. The latest python release is 3.11. 

https://circleci.com/developer/images/image/cimg/python

>  Each tag contains a complete Python version via pyenv. pip, pipenv, and poetry are pre-installed [...]

I am not sure if the warning is relevant for us though, because it addresses uses by normal human beings, not by a CI script running in a container. I would have to check, but I think all commands are run as root anyway and the container is destroyed after the website has been built.

_Originally posted by @joergbrech in https://github.com/hbrs-cse/Modellbildung-und-Simulation/issues/456#issuecomment-1323364434_

### PR DESCRIPTION
**Pull request by PhiSpel**
# Description

closes #460 
like #458 but with `cards` instead of `grid-item-card`

## Checklist

 - [x] This pull request is associated to an issue
 - [x] Add someone else as reviewer and wait for approval before merging.

### CODE REVIEW

**Comment by PhiSpel** [comment]
Now, it looks better, see [here](https://output.circle-artifacts.com/output/job/2ab092b5-7cfe-47c9-88b6-4930e29c4069/artifacts/0/html/00_einleitung/01_motivation.html).

Only remaining issue is that the CSS variable `--sd-color-card-header` needs to be changed to #00000008 instead of transparent, see [here](https://sphinx-design.readthedocs.io/en/furo-theme/css_variables.html). I just need to find the right file to put this information...

**Comment by PhiSpel** [comment]
running the "live code" function does not work, as the kernel seems to run on python instead of octave. This should be different on the main, though, as circleCI builds before did not work with live code at all

**Comment by PhiSpel** [comment]
> running the "live code" function does not work, as the kernel seems to run on python instead of octave (it does work correctly in mybinder). This should be different on the main, though, as circleCI builds before did not work with live code at all

**Comment by PhiSpel** [comment]
@Florian314 what do you think about the layout, for example [here](https://output.circle-artifacts.com/output/job/2ab092b5-7cfe-47c9-88b6-4930e29c4069/artifacts/0/html/00_einleitung/01_motivation.html)?

**Comment by PhiSpel** [comment]
Usually, one should be able to define custom styles in a `_static/custom.css` file within the project directory. I am afraid this is not accessed by jupyter book, see [e9abf86](https://github.com/hbrs-cse/Modellbildung-und-Simulation/pull/461/commits/e9abf86a9193e31dcbc6d5019a383109db9783fd)

[These](https://getbootstrap.com/docs/4.0/utilities/colors/) colors are accessible by the `:header-style:` keyword, of which `bg-light` seems to be the most sensible.

So, @Florian314, please look at the layout of the cards in "Das Stauproblem - Motivation zur Benutzung dieses Buches" and "Verwendung dieses Buches". What's your opinion on them?

When I have the feedback, I can adapt the 40-some other files.

**Comment by Florian314** [comment]
image
The box in a box looks strange to me

**Comment by Florian314** [comment]
image
This looks the best if you can delet the line below "Voraussetzungen"

**Comment by PhiSpel** [comment]
Actually, I just realized, that the boxes are now the same as the old ones:

image

@Florian314 Isn't this just fine / even better?

**Comment by Florian314** [comment]
yeah, i personely like the old ones the most

**Pull request merged**
