### PR TITLE
Update requirements.txt

### LINKED ISSUE #511: upgrade to jupyter-book==0.15.1
a lot happened recently. maybe, we should upgrade

### PR DESCRIPTION
**Pull request by PhiSpel**
# Description
closes #511 

## Checklist

 - [x] This pull request is associated to an issue
 - [x] Add someone else as reviewer and wait for approval before merging.

### CODE REVIEW

**Comment by PhiSpel** [comment]
@joergbrech I would be glad to have your approval before upgrading :)

**Comment by PhiSpel** [comment]
Oh, hold on, extra_navbar does not do what it should!

**Comment by joergbrech** [comment]
Ok. So we wait?

**Comment by PhiSpel** [comment]
Yes, I suggest we wait. Or use 0.14.x for now, but I think it makes more sense to wait a bit. 0.13.2 is fine for now, too.

**Pull request merged**
